%SUBROUTINE DRIVING DRAG FORCE
function [FDRGN,FDRGT]=AFMFORCEDRAG (FUN2,FUN3,FUN4,M3,VN,VT)
%	CALCULATE DRAG FORCES (NORMAL AND TANGENTIAL TO COLLECTOR SURFACE). 
	FDRGN = FUN2*M3*VN;
	FDRGT = FUN3/FUN4*M3*VT;
end
