%     SUBROUTINE VDW FORCE (N)
function [FVDW,FVDW2,Hasp_colloid,Hasp_domain]=AFMFORCEVDW (X,Y,Z,A132,AG,AP,ASPcolloid,ASPdomain,NASP,RMODE,xcap,ycap,zcap,xasp_domain,yasp_domain,zasp_domain,H,HS,LAMBDAVDW,A11,...
    A22,A33,AC1C1,AC2C2,T1,T2,VDWMODE,AFM_asp_tracking_RMODE3)
global LTLT
A12 = (A11^0.5)*(A22^0.5);
A1C2 = (A11^0.5)*(AC2C2^0.5) ;
A13 = (A11^0.5)*(A33^0.5);
AC12 = (AC1C1^0.5)*(A22^0.5);
AC1C2 = (AC1C1^0.5)*(AC2C2^0.5);
AC13 = (AC1C1^0.5)*(A33^0.5);
A23 = (A22^0.5)*(A33^0.5);
AC23 = (AC2C2^0.5)*(A33^0.5) ;
% asperitis separation distance arrays
Hasp_colloid =[];
Hasp_domain =[];
FVDW2 = [];

%  	CALC VDW (SPHERE-SPHERE GEOMETRY JUSTifIED BY LINEAR APPROXIMATION) Gregory retarded vdw energy 1981 from Elimelech Part. Dep book
if (VDWMODE==1)
    if (RMODE==0)   %SMOOTH SURFACE ON BOTH
        % determine geometry factor for smooth surfaces
        AEFF = AP*AG/(AP+AG);
        FVDW = -(A132*AEFF/(6*H^2.0))... %(SPHERE-SPHERE GEOMETRY) -RETARDED VAN DER WAALS EXPRESSION DERIVED FROM ENERGY GIVEN BY NIR 1977 INCLUDING RETARDATION FROM GREGORY 1981
            *(LAMBDAVDW/(LAMBDAVDW+5.32*H));
    end
    if (RMODE==1)   %ASPERITIES ON COLLOID
        % determine geometry factor for smooth surfaces
        AEFF = AP*AG/(AP+AG);
        % determine geometry factor for asperities
        AEFFASP = ASPcolloid*AG/(ASPcolloid+AG);
        H2 = H + ASPcolloid; %SEPARATION DISTANCE BETWEEN UNDERLYING SMOOTH COLLECTOR AND COLLOID
        %               CALCULATE VDW INTERACTION BETWEEN COLLOID AND COLLECTOR (SPHERE-SPHERE)
        FVDW1 = -(A132*AEFF/(6*H2^2.0))...
            *(LAMBDAVDW/(LAMBDAVDW+5.32*H2));
        %%               CALCULATE VDW INTERACITON BETWEEN ASPERTIES AND COLLECTOR (SPHERE-SPHERE)
        % vectorized calculation for array of separation distances
        Hasp_colloid = ycap-AG-ASPcolloid;
        % calculate only for asperities inside Hthreshold 
        c=Hasp_colloid<=1/LTLT*ASPcolloid;        
        if sum(c)>=1
            %extract valid separation distances
            Hasp_colloid=Hasp_colloid(c);
            FVDW2 = -(A132*AEFFASP./(6*Hasp_colloid.^2.0))...
                .*(LAMBDAVDW./(LAMBDAVDW+5.32*Hasp_colloid));
        else
            FVDW2 = 0.0;
        end
        %%               CALCULATE TOTAL INTERACTION                                                                                                                                                                                                                                                                                                                                                                                         CTION
        FVDW = FVDW1 + sum(FVDW2);
    end
    if (RMODE==2)   %ASPERITIES ON domain
        % determine geometry factor for smooth surfaces
        AEFF = AP*AG/(AP+AG);
        % determine geometry factor for asperities
        AEFFASP = ASPdomain*AG/(ASPdomain+AG);
        H2 = HS; %SEPARATION DISTANCE BETWEEN UNDERLYING SMOOTH COLLECTOR AND COLLOID
        %               CALCULATE VDW INTERACTION BETWEEN COLLOID AND COLLECTOR (SPHERE-SPHERE)
        FVDW1 = -(A132*AEFF/(6*H2^2.0))...
            *(LAMBDAVDW/(LAMBDAVDW+5.32*H2));
        %               CALCULATE VDW INTERACITON BETWEEN ASPERTIES AND COLLOID (SPHERE-SPHERE)
        % vectorized calculation for array of separation distances
        % array of distances between asperity centers and colloid center
        RXYZ = ((X-xasp_domain).*(X-xasp_domain)+(Y-yasp_domain).*(Y-yasp_domain) + (Z-zasp_domain).*(Z-zasp_domain)).^0.5;
        % factor of projection on  Y component (array)
        facY =  (Y-AG)./RXYZ;
        % separation distance between asperity and colloid surface
        Hasp_domain = RXYZ-AP-ASPdomain; 
        % calculate only for asperities inside Hthreshold 
        c=Hasp_domain<=1/LTLT*ASPdomain;
        if sum(c)>=1
            %extract valid separation distances
            Hasp_domain=Hasp_domain(c);
            facY = facY(c);
             FVDW2 = -(A132*AEFFASP./(6*Hasp_domain.^2.0))...
            .*(LAMBDAVDW./(LAMBDAVDW+5.32*Hasp_domain));
        else
            FVDW2 = 0.0;
        end
        % CALCULATE TOTAL INTERACTION
        FVDW = FVDW1 + sum(facY.*FVDW2);
    end
    % RMODE 3 treatment assumes equivalent fine scale roughness on
    % both surfaces because of fractal nature of roughness
    if (RMODE==3)    %ASPERITIES ON BOTH SURFACES
        % determine geometry factor for smooth surfaces
        AEFF = AP*AG/(AP+AG);
        % determine geometry factor for asperities
        AEFFASP = ASPdomain*ASPcolloid/(ASPdomain+ASPcolloid);
        % SEPARATION DISTANCE BETWEEN SMOOTH SURFACES
        H2 = ((X-0)*(X-0)+(Y-0)*(Y-0)+(Z-0)*(Z-0))^0.5-AP-AG;
        %               CALCULATE VDW INTERACTION BETWEEN COLLOID AND COLLECTOR (SPHERE-SPHERE)
        FVDW1 = -(A132*AEFF/(6*H2^2.0))...
            *(LAMBDAVDW/(LAMBDAVDW+5.32*H2));
        %               CALCULATE VDW INTERACTION BETWEEN ASPERITIES (SPHERE-SPHERE GEOMETRY JUSTifIED BY LINEAR APPROXIMATION) Gregory retarded vdw energy 1981 from Elimelech Part. Dep book
        % loop through one colloid asperity interacting with
        % a subdomain of asperities in ZOI
        % pralocate array of asperities contributions to interaction
        FVDW2 = NaN(1,length(xcap));
        % define bounds of zoi subset
        Rsubdomain = 2*ASPdomain;
        % determine smaller asperity size
        if ASPdomain<=ASPcolloid
            ASPsmaller = ASPdomain;
        else
            ASPsmaller = ASPcolloid;
        end
        %
        for i=1:length(xcap)
            % vectorized calculation for array of separation distances
            xcol = xcap(i);
            ycol = ycap(i);
            zcol = zcap(i);
            % call function to track asperities in subset of ZOI on the collector near projected colloid asperity location
            [xasp,yasp,zasp]=AFM_asp_tracking_RMODE3(xcol,ycol,zcol,AG,Rsubdomain,ASPdomain);
            Harray = ((xcol-xasp).*(xcol-xasp)+(ycol-yasp).*(ycol-yasp)+(zcol-zasp).*(zcol-zasp)).^0.5-ASPcolloid-ASPdomain;
            % find minnimum separtion distance
            [Hmin,imin] = min(Harray);
            % calculate only for asperities inside Hthreshold

            if Hmin<=1/LTLT*ASPsmaller
                % array of total interaction of a single colloid asperity with
                % all domain asperities
                FVDWoneasp = -(A132*AEFFASP./(6*Hmin.^2.0))...
                    .*(LAMBDAVDW./(LAMBDAVDW+5.32*Hmin));
                % array of distances between colloid asperity center and domain asperities centers
                RXYZ = ((xcol-xasp(imin)).*(xcol-xasp(imin))+(ycol-yasp(imin)).*(ycol-yasp(imin)) + (zcol-zasp(imin)).*(zcol-zasp(imin))).^0.5;
                % calculate unit vectors pointing from domains asperity to
                % colloid asperity center. DLVO forces contribution is only in
                % Y (laterals cancel each other)
                unity = (ycol-yasp(imin))./RXYZ;
                %disp(unity)
                % Correct array of interactions to component on Y axis
                FVDW2(i) = unity.*FVDWoneasp;
            else
                FVDW2(i)=0.0;
            end
        end
        %  CALCULATE TOTAL INTERACTION
        FVDW = FVDW1 + sum(FVDW2);
    end
end
% VDW EXPRESSION for coatings DERIVED FROM EXPRESION DEVELOPED BY Nir 1977 AND Vincent 1973.
% RETARDATION FACTOR AS SUGGESTED BY Ho AND Higuchi 1968
if (VDWMODE==2)
    ACP = AP-T1;
    ACG = AG-T2;
    COEFH1 = H ;
    COEFH2 = H+T1;
    COEFH3 = H+T2;
    COEFH4 = H+T1+T2;
    COEFA1 = ACP+T1;
    COEFA2 = ACG+T2;
    COEF = ACP+ACG+T1+T2;
    COEF2 = ACP+ACG+T2;
    COEF3 = ACP+ACG+T1;
    COEF4 = ACP+ACG;
    COEF5 = H+ACP+ACG+T1+T2;
    FVDW = -(AC1C2-AC23-AC13+A33)*...
        (LAMBDAVDW/(LAMBDAVDW+11.12*COEFH1)*...
        (4*COEFA1*COEFA2*COEF5*(1/(COEFH1^2+2*COEFH1*COEF)^2.0...
        +1/(COEFH1^2+2*COEFH1*COEF+4*COEFA1*COEFA2)^2)...
        -2*COEF5*(1/(COEFH1^2+2*COEFH1*COEF)...
        -1/(COEFH1^2+2*COEFH1*COEF+4*COEFA1*COEFA2)))...
        +11.12*LAMBDAVDW/(LAMBDAVDW+11.12*COEFH1)^2*...
        (2*COEFA1*COEFA2/(COEFH1^2+2*COEFH1*COEF)...
        +2*COEFA1*COEFA2/(COEFH1^2+2*COEFH1*COEF...
        +4*COEFA1*COEFA2)...
        +log((COEFH1^2+2*COEFH1*COEF)/...
        (COEFH1^2+2*COEFH1*COEF+4*COEFA1*COEFA2))))/6.0...
        -(A1C2-AC1C2-A13+AC13)*...
        (LAMBDAVDW/(LAMBDAVDW+11.12*COEFH2)*...
        (4*ACP*COEFA2*COEF5*(1/(COEFH2^2+2*COEFH2*COEF2)^2.0...
        +1/(COEFH2^2+2*COEFH2*COEF2+4*ACP*COEFA2)^2)...
        -2*COEF5*(1/(COEFH2^2+2*COEFH2*COEF2)...
        -1/(COEFH2^2+2*COEFH2*COEF2+4*ACP*COEFA2)))...
        +11.12*LAMBDAVDW/(LAMBDAVDW+11.12*COEFH2)^2*...
        (2*ACP*COEFA2/(COEFH2^2+2*COEFH2*COEF2)...
        +2*ACP*COEFA2/(COEFH2^2+2*COEFH2*COEF2...
        +4*ACP*COEFA2)...
        +log((COEFH2^2+2*COEFH2*COEF2)/...
        (COEFH2^2+2*COEFH2*COEF2+4*ACP*COEFA2))))/6.0...
        -(AC12-A23-AC1C2+AC23)*...
        (LAMBDAVDW/(LAMBDAVDW+11.12*COEFH3)*...
        (4*COEFA1*ACG*COEF5*(1/(COEFH3^2+2*COEFH3*COEF3)^2.0...
        +1/(COEFH3^2+2*COEFH3*COEF3+4*COEFA1*ACG)^2)...
        -2*COEF5*(1/(COEFH3^2+2*COEFH3*COEF3)...
        -1/(COEFH3^2+2*COEFH3*COEF3+4*COEFA1*ACG)))...
        +11.12*LAMBDAVDW/(LAMBDAVDW+11.12*COEFH3)^2*...
        (2*COEFA1*ACG/(COEFH3^2+2*COEFH3*COEF3)...
        +2*COEFA1*ACG/(COEFH3^2+2*COEFH3*COEF3...
        +4*COEFA1*ACG)...
        +log((COEFH3^2+2*COEFH3*COEF3)/...
        (COEFH3^2+2*COEFH3*COEF3+4*COEFA1*ACG))))/6.0...
        -(A12-AC12-A1C2+AC1C2)*...
        (LAMBDAVDW/(LAMBDAVDW+11.12*COEFH4)*...
        (4*ACP*ACG*COEF5*(1/(COEFH4^2+2*COEFH4*COEF4)^2.0...
        +1/(COEFH4^2+2*COEFH4*COEF4+4*ACP*ACG)^2)...
        -2*COEF5*(1/(COEFH4^2+2*COEFH4*COEF4)...
        -1/(COEFH4^2+2*COEFH4*COEF4+4*ACP*ACG)))...
        +11.12*LAMBDAVDW/(LAMBDAVDW+11.12*COEFH4)^2*...
        (2*ACP*ACG/(COEFH4^2+2*COEFH4*COEF4)...
        +2*ACP*ACG/(COEFH4^2+2*COEFH4*COEF4...
        +4*ACP*ACG)...
        +log((COEFH4^2+2*COEFH4*COEF4)/...
        (COEFH4^2+2*COEFH4*COEF4+4*ACP*ACG))))/6;
end
if (VDWMODE==3)
    ACP = AP;
    ACG = AG-T2;
    COEFH1 = H ;
    COEFH2 = H+T2;
    COEFA2 = ACG+T2;
    COEF = ACP+ACG+T2;
    COEF2 = ACP+ACG;
    COEF3 = H+ACP+ACG+T2;
    FVDW = -(A1C2-AC23-A13+A33)*...
        (LAMBDAVDW/(LAMBDAVDW+11.12*COEFH1)*...
        (4*ACP*COEFA2*COEF3*(1/(COEFH1^2+2*COEFH1*COEF)^2.0...
        +1/(COEFH1^2+2*COEFH1*COEF+4*ACP*COEFA2)^2)...
        -2*COEF3*(1/(COEFH1^2+2*COEFH1*COEF)...
        -1/(COEFH1^2+2*COEFH1*COEF+4*ACP*COEFA2)))...
        +11.12*LAMBDAVDW/(LAMBDAVDW+11.12*COEFH1)^2*...
        (2*ACP*COEFA2/(COEFH1^2+2*COEFH1*COEF)...
        +2*ACP*COEFA2/(COEFH1^2+2*COEFH1*COEF...
        +4*ACP*COEFA2)...
        +log((COEFH1^2+2*COEFH1*COEF)/...
        (COEFH1^2+2*COEFH1*COEF+4*ACP*COEFA2))))/6.0...
        -(A12-A23-A1C2+AC23)*...
        (LAMBDAVDW/(LAMBDAVDW+11.12*COEFH2)*...
        (4*ACP*ACG*COEF3*(1/(COEFH2^2+2*COEFH2*COEF2)^2.0...
        +1/(COEFH2^2+2*COEFH2*COEF2+4*ACP*ACG)^2)...
        -2*COEF3*(1/(COEFH2^2+2*COEFH2*COEF2)...
        -1/(COEFH2^2+2*COEFH2*COEF2+4*ACP*ACG)))...
        +11.12*LAMBDAVDW/(LAMBDAVDW+11.12*COEFH2)^2*...
        (2*ACP*ACG/(COEFH2^2+2*COEFH2*COEF2)...
        +2*ACP*ACG/(COEFH2^2+2*COEFH2*COEF2...
        +4*ACP*ACG)...
        +log((COEFH2^2+2*COEFH2*COEF2)/...
        (COEFH2^2+2*COEFH2*COEF2+4*ACP*ACG))))/6;
end
if (VDWMODE==4)
    ACP = AP-T1;
    ACG = AG;
    COEFH1 = H ;
    COEFH2 = H+T1;
    COEFA1 = ACP+T1;
    COEF = ACP+ACG+T1;
    COEF2 = ACP+ACG;
    COEF3 = H+ACP+ACG+T1;
    FVDW = -(AC12-A23-AC13+A33)*...
        (LAMBDAVDW/(LAMBDAVDW+11.12*COEFH1)*...
        (4*COEFA1*ACG*COEF3*(1/(COEFH1^2+2*COEFH1*COEF)^2.0...
        +1/(COEFH1^2+2*COEFH1*COEF+4*COEFA1*ACG)^2)...
        -2*COEF3*(1/(COEFH1^2+2*COEFH1*COEF)...
        -1/(COEFH1^2+2*COEFH1*COEF+4*COEFA1*ACG)))...
        +11.12*LAMBDAVDW/(LAMBDAVDW+11.12*COEFH1)^2*...
        (2*COEFA1*ACG/(COEFH1^2+2*COEFH1*COEF)...
        +2*COEFA1*ACG/(COEFH1^2+2*COEFH1*COEF...
        +4*COEFA1*ACG)...
        +log((COEFH1^2+2*COEFH1*COEF)/...
        (COEFH1^2+2*COEFH1*COEF+4*COEFA1*ACG))))/6.0...
        -(A12-AC12-A13+AC13)*...
        (LAMBDAVDW/(LAMBDAVDW+11.12*COEFH2)*...
        (4*ACP*ACG*COEF3*(1/(COEFH2^2+2*COEFH2*COEF2)^2.0...
        +1/(COEFH2^2+2*COEFH2*COEF2+4*ACP*ACG)^2)...
        -2*COEF3*(1/(COEFH2^2+2*COEFH2*COEF2)...
        -1/(COEFH2^2+2*COEFH2*COEF2+4*ACP*ACG)))...
        +11.12*LAMBDAVDW/(LAMBDAVDW+11.12*COEFH2)^2*...
        (2*ACP*ACG/(COEFH2^2+2*COEFH2*COEF2)...
        +2*ACP*ACG/(COEFH2^2+2*COEFH2*COEF2...
        +4*ACP*ACG)...
        +log((COEFH2^2+2*COEFH2*COEF2)/...
        (COEFH2^2+2*COEFH2*COEF2+4*ACP*ACG))))/6;
end
if (abs(FVDW)<1.0E-30)
    FVDW = 0.0;
end
end