%     SUBROUTINE GRAVITY
%     GRAVITATIONAL FORCE - BECAUSE GRAVFACT IS READ AS -1 FOR CONCURRENT, +1 FOR COUNTERCURRENT FLOW, WE REVERSE THE SIGN BELOW TO REFLECT FLOW COMING FROM -Z DIRECTION
function FG=AFMGRAVITY(GRAVFACT,AP,G,RHOP,RHOW,PI)
      FG = -GRAVFACT*(4.0/3.0)*(PI)*(AP^3)*(RHOP-RHOW)*G;
end