function [LOCS] = importCHAOlocs(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  LOCS = importLOCS(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  LOCS = importCHAOlocs(FILE, SHEET) reads from the specified worksheet.
%
%  LOCS = importCHAOlocs(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  LOCS = importCHAOlocs("J:\Google Drive\MATLAB current projects\AFM module\Chao data\1mM 1nN.xlsm", "data", [2, 7201]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Aug-2021 12:59:29

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 7201];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "B" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Xpositionnm", "Ypositionnm"];
opts.SelectedVariableNames = ["Xpositionnm", "Ypositionnm"];
opts.VariableTypes = ["double", "double"];

% Import the data
LOCS = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "B" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    LOCS = [LOCS; tb]; %#ok<AGROW>
end

end