%Force AB_Sphere-Plate_RMODE (J)
function[F_AB]=F_AB_SP_RMODE(H,lambdaAB,aasp,nAB,gammaoAB,ho,...
                             RMODE,a1,Nco)
    if RMODE==1
        F_AB=nAB*(1-lambdaAB/aasp+(1+lambdaAB/aasp)*...
               exp(-2*aasp/lambdaAB))*2*pi*...
               aasp*gammaoAB.*exp(-(H-ho)/lambdaAB);
    end
    if RMODE==2
        aeff=2*aasp*a1/(aasp+a1);%%[m] effective radius
         %Corecction factor
        correc_factor=(1-lambdaAB/aeff+lambdaAB^2/(2*aeff^2)-...
            4*aeff/(3*lambdaAB)*exp(-2*aeff/lambdaAB)-...
            (1+lambdaAB/aeff+lambdaAB^2/(2*aeff^2))*...
            exp(-4*aeff/lambdaAB));
        
        F_AB=nAB*correc_factor*pi*aeff*gammaoAB.*...
              exp(-(H-ho)/lambdaAB);
    end
    if RMODE==3
        aeff=2*aasp*aasp/(aasp+aasp);%[m] effective radius
         %Corecction factor
        correc_factor=(1-lambdaAB/aeff+lambdaAB^2/(2*aeff^2)-...
            4*aeff/(3*lambdaAB)*exp(-2*aeff/lambdaAB)-...
            (1+lambdaAB/aeff+lambdaAB^2/(2*aeff^2))*...
            exp(-4*aeff/lambdaAB));
        
        F_AB=Nco*nAB*correc_factor*pi*aeff*gammaoAB.*...
              exp(-(H-ho)/lambdaAB);  
    end
    % make zero Force values calculated for H>aasp 
    %(comply with Dejarguin aproximation)
    c=H>aasp;
    F_AB(c)=0.0;    
end