%Force AB_Sphere-Plate_colloid_plate (N)
function[ForceAB]=F_AB_SP_colloid_plate(H,lambdaAB,a1,gammaoAB,ho)
ForceAB=(1-lambdaAB/a1+(1+lambdaAB/a1)*...
    exp(-2*a1/lambdaAB))*2*pi*a1*gammaoAB.*...
    exp(-(H-ho)/lambdaAB);