%Force EDL_Sphere-Plate_colloid_plate (N)
function[F_EDL]=F_EDL_SP_colloid_plate(H,theta,eps,K,kB,T,z,...
                     zeta1,e_charge,zeta2,a1)
    F_EDL=(theta)*(64*pi*eps*(kB*T/z/e_charge)^2*...
                tanh(z*e_charge*zeta1/4/kB/T)...
                *tanh(z*e_charge*zeta2/4/kB/T)*...
                ((K*a1-1).*exp(-K*H)+(K*a1+1).*exp(-K*(H+2*a1))));
end
