function UPFLUX_header = import_header_UPFLUX(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  UPFLUXAGPROJECT3MM = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a cell array.
%
%  UPFLUXAGPROJECT3MM = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  UPFLUXAGPROJECT3MM = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  UPFLUX_header = import_header_UPFLUX("J:\Google Drive\MATLAB current projects\Upscale\UPFLUX-Ag_project-3mM.xlsx", "FAVATT", [1, 4]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Dec-2020 16:53:03

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 4];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 38);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":AL" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["NPART", "VarName2", "VSUPms1", "e05", "RLIMm", "e05_1", "POROSITY", "VarName8", "AGm", "VarName10", "RBm", "VarName12", "TTIMEs", "VarName14", "ATTMODE", "VarName16", "SLIPm", "e07", "RMODE", "VarName20", "ASPm", "e08", "ASP2m", "e07_1", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38"];
opts.SelectedVariableNames = ["NPART", "VarName2", "VSUPms1", "e05", "RLIMm", "e05_1", "POROSITY", "VarName8", "AGm", "VarName10", "RBm", "VarName12", "TTIMEs", "VarName14", "ATTMODE", "VarName16", "SLIPm", "e07", "RMODE", "VarName20", "ASPm", "e08", "ASP2m", "e07_1", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38], "EmptyFieldRule", "auto");

% Import the data
UPFLUX_header = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":AL" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    UPFLUX_header = [UPFLUX_header; tb]; %#ok<AGROW>
end

%% Convert to output type
UPFLUX_header = table2cell(UPFLUX_header);
numIdx = cellfun(@(x) ~isnan(str2double(x)), UPFLUX_header);
UPFLUX_header(numIdx) = cellfun(@(x) {str2double(x)}, UPFLUX_header(numIdx));
end